name: release-please

on:
  push:
    branches:
      - main  

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: rust
          package-name: xcode-discord-rpc
          include-v-in-tag: true
          
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}

